### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by banesullivan**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by banesullivan** [comment]
Pinging @grlee77 - doe this address your concerns in https://github.com/conda-forge/pyvista-feedstock/pull/1#issuecomment-493674252 ?

**Comment by banesullivan** [comment]
@conda-forge-admin, please rerender

**Comment by grlee77** [comment]
Yes, this looks good to me

**Comment by banesullivan** [comment]
Thanks!

**Pull request merged**
